/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAgentRouteImport } from './routes/api/agent'
import { Route as ApiArkRouteImport } from './routes/api/ark'
import { Route as ApiAssistantRouteImport } from './routes/api/assistant'
import { Route as ApiChatStreamRouteImport } from './routes/api/chat-stream'
import { Route as ApiContentAgentRouteImport } from './routes/api/content-agent'
import { Route as ApiModelarkRouteImport } from './routes/api/modelark'
import { Route as ApiModelarkDirectorRouteImport } from './routes/api/modelark-director'
import { Route as ApiReferenceUploadRouteImport } from './routes/api/reference-upload'
import { Route as ApiSpeechRouteImport } from './routes/api/speech'
import { Route as ApiZenmuxRouteImport } from './routes/api/zenmux'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArkRoute = ApiArkRouteImport.update({
  id: '/api/ark',
  path: '/api/ark',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantRoute = ApiAssistantRouteImport.update({
  id: '/api/assistant',
  path: '/api/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatStreamRoute = ApiChatStreamRouteImport.update({
  id: '/api/chat-stream',
  path: '/api/chat-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentAgentRoute = ApiContentAgentRouteImport.update({
  id: '/api/content-agent',
  path: '/api/content-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelarkRoute = ApiModelarkRouteImport.update({
  id: '/api/modelark',
  path: '/api/modelark',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelarkDirectorRoute = ApiModelarkDirectorRouteImport.update({
  id: '/api/modelark-director',
  path: '/api/modelark-director',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceUploadRoute = ApiReferenceUploadRouteImport.update({
  id: '/api/reference-upload',
  path: '/api/reference-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpeechRoute = ApiSpeechRouteImport.update({
  id: '/api/speech',
  path: '/api/speech',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZenmuxRoute = ApiZenmuxRouteImport.update({
  id: '/api/zenmux',
  path: '/api/zenmux',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/ark': typeof ApiArkRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/api/chat-stream': typeof ApiChatStreamRoute
  '/api/content-agent': typeof ApiContentAgentRoute
  '/api/modelark': typeof ApiModelarkRoute
  '/api/modelark-director': typeof ApiModelarkDirectorRoute
  '/api/reference-upload': typeof ApiReferenceUploadRoute
  '/api/speech': typeof ApiSpeechRoute
  '/api/zenmux': typeof ApiZenmuxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/ark': typeof ApiArkRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/api/chat-stream': typeof ApiChatStreamRoute
  '/api/content-agent': typeof ApiContentAgentRoute
  '/api/modelark': typeof ApiModelarkRoute
  '/api/modelark-director': typeof ApiModelarkDirectorRoute
  '/api/reference-upload': typeof ApiReferenceUploadRoute
  '/api/speech': typeof ApiSpeechRoute
  '/api/zenmux': typeof ApiZenmuxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/ark': typeof ApiArkRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/api/chat-stream': typeof ApiChatStreamRoute
  '/api/content-agent': typeof ApiContentAgentRoute
  '/api/modelark': typeof ApiModelarkRoute
  '/api/modelark-director': typeof ApiModelarkDirectorRoute
  '/api/reference-upload': typeof ApiReferenceUploadRoute
  '/api/speech': typeof ApiSpeechRoute
  '/api/zenmux': typeof ApiZenmuxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/agent'
    | '/api/ark'
    | '/api/assistant'
    | '/api/chat-stream'
    | '/api/content-agent'
    | '/api/modelark'
    | '/api/modelark-director'
    | '/api/reference-upload'
    | '/api/speech'
    | '/api/zenmux'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/agent'
    | '/api/ark'
    | '/api/assistant'
    | '/api/chat-stream'
    | '/api/content-agent'
    | '/api/modelark'
    | '/api/modelark-director'
    | '/api/reference-upload'
    | '/api/speech'
    | '/api/zenmux'
  id:
    | '__root__'
    | '/'
    | '/api/agent'
    | '/api/ark'
    | '/api/assistant'
    | '/api/chat-stream'
    | '/api/content-agent'
    | '/api/modelark'
    | '/api/modelark-director'
    | '/api/reference-upload'
    | '/api/speech'
    | '/api/zenmux'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAgentRoute: typeof ApiAgentRoute
  ApiArkRoute: typeof ApiArkRoute
  ApiAssistantRoute: typeof ApiAssistantRoute
  ApiChatStreamRoute: typeof ApiChatStreamRoute
  ApiContentAgentRoute: typeof ApiContentAgentRoute
  ApiModelarkRoute: typeof ApiModelarkRoute
  ApiModelarkDirectorRoute: typeof ApiModelarkDirectorRoute
  ApiReferenceUploadRoute: typeof ApiReferenceUploadRoute
  ApiSpeechRoute: typeof ApiSpeechRoute
  ApiZenmuxRoute: typeof ApiZenmuxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ark': {
      id: '/api/ark'
      path: '/api/ark'
      fullPath: '/api/ark'
      preLoaderRoute: typeof ApiArkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant': {
      id: '/api/assistant'
      path: '/api/assistant'
      fullPath: '/api/assistant'
      preLoaderRoute: typeof ApiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-stream': {
      id: '/api/chat-stream'
      path: '/api/chat-stream'
      fullPath: '/api/chat-stream'
      preLoaderRoute: typeof ApiChatStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content-agent': {
      id: '/api/content-agent'
      path: '/api/content-agent'
      fullPath: '/api/content-agent'
      preLoaderRoute: typeof ApiContentAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/modelark': {
      id: '/api/modelark'
      path: '/api/modelark'
      fullPath: '/api/modelark'
      preLoaderRoute: typeof ApiModelarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/modelark-director': {
      id: '/api/modelark-director'
      path: '/api/modelark-director'
      fullPath: '/api/modelark-director'
      preLoaderRoute: typeof ApiModelarkDirectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reference-upload': {
      id: '/api/reference-upload'
      path: '/api/reference-upload'
      fullPath: '/api/reference-upload'
      preLoaderRoute: typeof ApiReferenceUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/speech': {
      id: '/api/speech'
      path: '/api/speech'
      fullPath: '/api/speech'
      preLoaderRoute: typeof ApiSpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zenmux': {
      id: '/api/zenmux'
      path: '/api/zenmux'
      fullPath: '/api/zenmux'
      preLoaderRoute: typeof ApiZenmuxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAgentRoute: ApiAgentRoute,
  ApiArkRoute: ApiArkRoute,
  ApiAssistantRoute: ApiAssistantRoute,
  ApiChatStreamRoute: ApiChatStreamRoute,
  ApiContentAgentRoute: ApiContentAgentRoute,
  ApiModelarkRoute: ApiModelarkRoute,
  ApiModelarkDirectorRoute: ApiModelarkDirectorRoute,
  ApiReferenceUploadRoute: ApiReferenceUploadRoute,
  ApiSpeechRoute: ApiSpeechRoute,
  ApiZenmuxRoute: ApiZenmuxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
